%%% This Maltab code calculated nonequilibrium spin-dependent distribution function
%%%  generated by the magnetization dynamics in FI/S'S structure
clear all
for indF=1:16
    
    indF
clearvars -except indF

for indDiff=10:10

  if (indF==1)
        dRsuper=1.5;
%fnameComm='h3Rmax021D3d0DN1d5DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN1d5Diff' num2str(indDiff) 'CplVar'];
     end
      if (indF==2)
          dRsuper=1.4;
fnameComm='h3Rmax021D3d0DN1d4DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN1d4Diff' num2str(indDiff) 'CplVar'];
      end
       if (indF==3)
         dRsuper=1.3;
fnameComm='h3Rmax021D3d0DN1d3DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN1d3Diff' num2str(indDiff) 'CplVar'];
       end
        if (indF==4)
          dRsuper=1.2;
 fnameComm='h3Rmax021D3d0DN1d2DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN1d2Diff' num2str(indDiff) 'CplVar'];
        end
         if (indF==5)
          dRsuper=1.1;
 fnameComm='h3Rmax021D3d0DN1d1DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN1d1Diff' num2str(indDiff) 'CplVar'];
         end
          if (indF==6)
           dRsuper=1.0;
 fnameComm='h3Rmax021D3d0DN1d0DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN1d0Diff' num2str(indDiff) 'CplVar'];
            end          
            if (indF==7)
           dRsuper=0.9;
 fnameComm='h3Rmax021D3d0DN0d9DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d9Diff' num2str(indDiff) 'CplVar'];
            end
            if (indF==8)
           dRsuper=0.8;
 fnameComm='h3Rmax021D3d0DN0d8DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d8Diff' num2str(indDiff) 'CplVar'];
            end
               if (indF==9)
              dRsuper=0.7;
 fnameComm='h3Rmax021D3d0DN0d7DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d7Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==10)
            dRsuper=0.6;
 fnameComm='h3Rmax021D3d0DN0d6DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d6Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==11)
           dRsuper=0.5;
 fnameComm='h3Rmax021D3d0DN0d5DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d5Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==12)
           dRsuper=0.4;
 fnameComm='h3Rmax021D3d0DN0d4DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d4Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==13)
           dRsuper=0.3;
 fnameComm='h3Rmax021D3d0DN0d3DiffNonConstCplVar';
%fnameComm='h3Rmax041D3d0DN0d3DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN0d3Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==14)
           dRsuper=0.2;
 fnameComm='h3Rmax021D3d0DN0d2DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d2Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==15)
           dRsuper=0.1;
 fnameComm='h3Rmax021D3d0DN0d1DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d1Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==16)
           dRsuper=0.0;
 fnameComm='h3Rmax021D3d0DN0d0DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d0Diff' num2str(indDiff) 'CplVar'];
               end
            
fname0=['...']; path to the folder with spectral functions
fname0Res=['...']; where to put results

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
grd=-2.0;
beta=-1;
%dnSO=3.0;
timp=1;
fileSave=[fname0Res fnameComm 'tSO1ResKin'];
OmM=0.02;
G=0.1;

lengthE=174;
lengthE=348;

StepE=0.02;
lengthE1=lengthE-0.0/StepE;            


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%55555

TT=[];
DDiss=[];
DDiss1=[];
DDiss2=[];

    for dT=1:4:101                     
        
        indN=1;
        Temp=dT*0.01;
TT=[TT Temp];

 if (dT<100)     
     indN=2;

% fileDOS=[fname0 'DOST0' num2str(dT) 'h3Rmax021D3d0DN0d0DiffConst.dat'];
% fff=[fname0 'OPT0' num2str(dT) 'h3Rmax021D3d0DN0d0DiffConst'];
fileDOS=[fname0 'DOST0' num2str(dT) fnameComm '.dat'];
fileOp=[fname0 'OPT0' num2str(dT) fnameComm '.dat'];
fileSavemuS=[fname0Res fnameComm 'MUST0' num2str(dT) 'tSO05ResKin'];

if(dT<10) 
fileDOS=[fname0 'DOST00' num2str(dT) fnameComm '.dat'];
fileOp=[fname0 'OPT00' num2str(dT) fnameComm '.dat'];
fileSavemuS=[fname0Res fnameComm 'MUST00' num2str(dT) 'tSO1ResKin'];
end

%fff1=[fff 'ResKin'];

%fileOp=[fff '.dat'];
%fileSave=fff1 ;  

fid = fopen(fileOp, 'r');  
Var1 = fscanf(fid,'%e%e%e%e',[4 inf]);
fclose(fid);
Var1=Var1';
x=Var1(:,1);
Op=Var1(:,2);
Magn=Var1(:,3);
Hex=Var1(:,4);

RN=0.5;
timpSO=timp*( 1 - tanh((x- RN)/0.025))/2 + 1;
%timpSO=timp*( 1 + tanh((x - max(x) + RN)/0.025))/2 + 0.5 ;
timpSO=timp;

StepX=x(2)-x(1);
lengthX=length(x);

fid = fopen(fileDOS, 'r');  
Var1 = fscanf(fid,'%e%e%e%e%e%e',[6 inf]);
fclose(fid);
Var1=Var1';
  
Er=Var1(:,1);
xr=Var1(:,2);

Rsuper=max(xr)-dRsuper;
   
Reg03r=Var1(:,3);
Img03r=Var1(:,4);  
Reg01r=Var1(:,5);  
Img01r=Var1(:,6);  

 end

Emax=max(Er);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (indN==1) 
Reg03r=zeros(size(Reg03r)) + 1;
Img03r=zeros(size(Reg03r));  
 
Reg01r=zeros(size(Reg03r));  
Img01r=zeros(size(Reg03r));  

Op=zeros(size(Op));

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% figure;
% plot(x,Op)
% hold on
% plot(x,Reg03)
% plot(x,Reg01)
% pause

indT=0;
Diss=0;
Diss1=0;
Diss2=0;
DissE=[];
EEE=[];

DDD=[];
SSS=[];
%for indE=1:(2*lengthE1)
    
%h1=figure;
%h2=figure;

muSTot=0;

    for indE=1:ceil(lengthE1)

    if(indE<lengthE1+1)
        
    for indX=1:lengthX
        
        indT=indT+1;

        x(indX)=xr(indT);
        E(indX)= Er(indT);

Reg03(indX)=Reg03r(indT);
Img03(indX)=Img03r(indT);  
 
Reg01(indX)=Reg01r(indT);  
Img01(indX)=Img01r(indT);  
     
    end
    end  %% end if E<
    
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%   
 if(indE>lengthE1)        
 for indX=1:lengthX    
 E(indX)= StepE*indE;
 Reg03(indX)=1.0;
 Img03(indX)=0;   
 Reg01(indX)=0;  
 Img01(indX)=0;          
 end
 end  %% end if E>
 %%%%%%%%%%%%%%%%%%%%%%%%%%%
   
    for ind=1:length(x)        
    
           DN=0.05;
    Diff(ind)=(1-DN)*( 1 - tanh((x(ind)- Rsuper)/0.025))/2 + DN ;
    
    if (indF==16)
    Diff(ind)=1;
    end
    end   
    
EE=E(1);
dnE=(tanh((EE+OmM)/(2*Temp))-tanh((EE)/(2*Temp)) )/OmM;
%%%%%%%%%%%%%%%

DT1 = Diff.*( 1- Img01.^2 + Img03.^2 - ...
     Reg01.^2 + Reg03.^2 )*1 ;   
            
       ST1= (Reg03.^2+beta*Img01.^2);
       
     H1=-  ( timpSO'.*ST1 + Reg03*(i*OmM + 2*G));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       

%dnE=1;
SourceX=0*Reg03 + 0*dnE*Reg03;
SourceX(length(Reg03))=dnE*Reg03(length(Reg03));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%StepX=x(2)-x(1);

A=zeros(length(x),length(x));

indY=1;
A(1,1) = - DT1(1)/StepX^2 + H1(indY) ;
A(1,2) =   DT1(1)/StepX^2  ;

indY=length(x);
A(indY,indY) =  - DT1(indY-1)/StepX^2 + H1(indY) ;
A(indY,indY-1) =  DT1(indY-1)/StepX^2  ;

for indY=2:(length(x)-1)
   % B(indY,indY)= H2(indY);

for indX=1:(length(x))
    
if (indX==indY) 
%A(indY,indX) = - 8*Diff(indX)/(4*StepX^2) ;
A(indY,indX) = - ( DT1(indX) + DT1(indX-1) )/StepX^2 + H1(indY) ;
end

if (indX==(indY-1)) 
A(indY,indX) = DT1(indX)/StepX^2 ;

end

if (indX==(indY+1))
A(indY,indX) = DT1(indX-1)/StepX^2 ;

end

end

end

SSource=[SourceX];
ySol= A\conj(SSource');

f1= ySol(1:length(x));
muS=f1.*Reg03';

% dM=max(x);
% muS1=0*muS';
% JJptX11=0;
% D=Op(1)
%  E0R= EE +j*G;
%  E0A= EE -j*G;
% Om0R =-j*E0R ;
% Om0A =-j*E0A ;
% xiR0 = -j*( sign(EE).*(  E0R.^2 - D^2 ).^(0.5)); 
% xiA0 = -j*( -sign(EE).*( E0A.^2 - D^2 ).^(0.5));
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% for n= 0:0    
%     timp2 = timp + 2*(pi*n)^2/dM^2;  
%     timp1 = timpSO.*ST1' + DT1'*(pi*n)^2/dM^2; 
%     muS1=  muS1 + ( dnE.*Reg03.^2./(timp1' + Reg03*(i*OmM + 2*G)))/(2*dM);
% 
% CHIA5R0 = chiA(xiA0,xiR0,Om0A,Om0R,D,timp2) ;
% JJptX11= JJptX11+ dnE.*CHIA5R0/(2*dM) ;
% 
%  end
% 
% for n= 1:20
%      timp2 = timp + 2*(pi*n)^2/dM^2;  
%     timp1 = timpSO.*ST1' + DT1'*(pi*n)^2/dM^2; 
% muS1=  muS1 + ( dnE.*Reg03.^2./(timp1' + Reg03*(i*OmM + 2*G)))/dM;
% 
% CHIA5R0 = chiA(xiA0,xiR0,Om0A,Om0R,D,timp2) ;
% JJptX11= JJptX11+ dnE.*CHIA5R0/(dM) ;
% end
% 
% muSTot= muSTot+muS*StepE;
% 
% 
% EEE=[EEE EE];
% 
% DDD=[DDD DT1(1)];
% SSS=[SSS ST1(1)];

Diss= Diss- (muS(length(muS)))*StepE;
%Diss1= Diss1- (muS1(length(muS1)))*StepE;
%Diss2= Diss2- JJptX11*StepE;

%save (fileSavemuS,'x', 'muSTot');

    end   
     
%%%%%%%%%%%%%%%%%%%%%%%%%
  
    DDiss=[DDiss 2*Diss];
    %DDiss1=[DDiss1 2*Diss1];
    %DDiss2=[DDiss2 2*Diss2];
        
    hold on
    end

 %figure
 plot(TT,DDiss/2)
 %hold on
 %plot(TT,-DDiss1*StepX)
 % plot(TT,DDiss2*StepX/4)

 save (fileSave,'TT', 'DDiss');
 
end

end

