%%% This Maltab code calculated corrections to the spectral functions
%%%  generated by the magnetization dynamics in FI/S'S structure


clear all
for indF=1:16
clearvars -except indF

indF
for indDiff=10:10


   if (indF==1)
        dRsuper=1.5;
%fnameComm='h3Rmax021D3d0DN1d5DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN1d5Diff' num2str(indDiff) 'CplVar'];
     end
      if (indF==2)
          dRsuper=1.4;
fnameComm='h3Rmax021D3d0DN1d4DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN1d4Diff' num2str(indDiff) 'CplVar'];
      end
       if (indF==3)
         dRsuper=1.3;
fnameComm='h3Rmax021D3d0DN1d3DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN1d3Diff' num2str(indDiff) 'CplVar'];
       end
        if (indF==4)
          dRsuper=1.2;
 fnameComm='h3Rmax021D3d0DN1d2DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN1d2Diff' num2str(indDiff) 'CplVar'];
        end
         if (indF==5)
          dRsuper=1.1;
 fnameComm='h3Rmax021D3d0DN1d1DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN1d1Diff' num2str(indDiff) 'CplVar'];
         end
          if (indF==6)
           dRsuper=1.0;
 fnameComm='h3Rmax021D3d0DN1d0DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN1d0Diff' num2str(indDiff) 'CplVar'];
            end          
            if (indF==7)
           dRsuper=0.9;
 fnameComm='h3Rmax021D3d0DN0d9DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d9Diff' num2str(indDiff) 'CplVar'];
            end
            if (indF==8)
           dRsuper=0.8;
 fnameComm='h3Rmax021D3d0DN0d8DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d8Diff' num2str(indDiff) 'CplVar'];
            end
               if (indF==9)
              dRsuper=0.7;
 fnameComm='h3Rmax021D3d0DN0d7DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d7Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==10)
            dRsuper=0.6;
 fnameComm='h3Rmax021D3d0DN0d6DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d6Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==11)
           dRsuper=0.5;
 fnameComm='h3Rmax021D3d0DN0d5DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d5Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==12)
           dRsuper=0.4;
 fnameComm='h3Rmax021D3d0DN0d4DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d4Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==13)
           dRsuper=0.3;
 fnameComm='h3Rmax021D3d0DN0d3DiffNonConstCplVar';
%fnameComm='h3Rmax041D3d0DN0d3DiffNonConstCplVar';
fnameComm=['h3Rmax021D3d0DN0d3Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==14)
           dRsuper=0.2;
 fnameComm='h3Rmax021D3d0DN0d2DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d2Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==15)
           dRsuper=0.1;
 fnameComm='h3Rmax021D3d0DN0d1DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d1Diff' num2str(indDiff) 'CplVar'];
               end
               if (indF==16)
           dRsuper=0.0;
 fnameComm='h3Rmax021D3d0DN0d0DiffNonConstCplVar';
 fnameComm=['h3Rmax021D3d0DN0d0Diff' num2str(indDiff) 'CplVar'];
               end
            
fname0=['...'];   % path to the folder with spectral fucntions
fname0Res=['...'];  % where to put results

            
               
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%55               


grd=-2.0;
beta=-1;
%dnSO=3.0;
timp=1;
fileSave=[fname0Res fnameComm 'tSO1ResSpec'];
OmM=0.02;
G=0.1;

lengthE=174;
lengthE=348;

StepE=0.02;
lengthE1=lengthE-0.0/StepE;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

TT=[];
DDiss=[];

    for dT=1:4:101
        
        indN=1;
       
        Temp=dT*0.01;

TT=[TT Temp];

 if (dT<100)
     
     indN=2;

fileDOS=[fname0 'DOST0' num2str(dT) fnameComm '.dat'];
fileOp=[fname0 'OPT0' num2str(dT) fnameComm '.dat'];
fileSavemuS=[fname0Res fnameComm 'MUST0' num2str(dT) 'tSO05ResSpec'];
if(dT<10) 
fileDOS=[fname0 'DOST00' num2str(dT) fnameComm '.dat'];
fileOp=[fname0 'OPT00' num2str(dT) fnameComm '.dat'];
fileSavemuS=[fname0Res fnameComm 'MUST00' num2str(dT) 'tSO05ResSpec'];
end

fid = fopen(fileOp, 'r');  
Var1 = fscanf(fid,'%e%e%e%e',[4 inf]);
fclose(fid);
Var1=Var1';
x=Var1(:,1);
Op=Var1(:,2);
Magn=Var1(:,3);
Hex=Var1(:,4);

RN=0.50;
timpSO=timp*( 1 - tanh((x- RN)/0.025))/2 + 1 ;

%timpSO=timp*( 1 + tanh((x - max(x) + RN)/0.025))/2 + 0.1 ;
%timpSO=timp*( 1 + tanh((x - max(x) + RN)/0.025))/2 + 0.5 ;
timpSO=timp;

StepX=x(2)-x(1);
lengthX=length(x);

fid = fopen(fileDOS, 'r');  
Var1 = fscanf(fid,'%e%e%e%e%e%e',[6 inf]);
fclose(fid);
Var1=Var1';
  
Er=Var1(:,1);
xr=Var1(:,2);

Rsuper=max(xr)-dRsuper;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Reg03r=Var1(:,3);
Img03r=Var1(:,4);  
Reg01r=Var1(:,5);  
Img01r=Var1(:,6);  

 end

Emax=max(Er);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (indN==1) 
Reg03r=zeros(size(Reg03r)) + 1;
Img03r=zeros(size(Reg03r));  
 
Reg01r=zeros(size(Reg03r));  
Img01r=zeros(size(Reg03r));  

Op=zeros(size(Op));

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %indN=2;
% if (indN==1) 
% Reg03=Reg03./Reg03;
% Img03=0*Img03;  
% Reg01=0*Reg01;  
% Img01=0*Img01;  
% end
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%

indT=0;
Diss=0;
DissE=[];
EEE=[];
DDDiss=[];

DDD=[];
SSS=[];

muSTot=0;

    for indE=1:ceil(lengthE1)-1

    if(indE<lengthE1)
        
    for indX=1:lengthX        
        indT=indT+1;
        x(indX)=xr(indT);
        E(indX)= Er(indT);
Reg03(indX)=Reg03r(indT);
Img03(indX)=Img03r(indT);  
Reg01(indX)=Reg01r(indT);  
Img01(indX)=Img01r(indT);        
    end
    
    indT1=indT;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    for indX=1:lengthX      
         indT1=indT1+1;      
Reg03Om5(indX)=Reg03r(indT1);
Img03Om5(indX)=Img03r(indT1);  
Reg01Om5(indX)=Reg01r(indT1);  
Img01Om5(indX)=Img01r(indT1);        
    end
    
    end  %% end if E<  
    
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
    if(indE>lengthE1-1)        
    for indX=1:lengthX
        
 E(indX)= StepE*indE;

 Reg03(indX)=1.0;
 Img03(indX)=0;  
 Reg01(indX)=0;  
 Img01(indX)=0;  
 
 Reg03Om5(indX)=1.0;
Img03Om5(indX)=0;  
Reg01Om5(indX)=0;  
Img01Om5(indX)=0;        
         
    end
    end  %% end if E>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5

gR03Om0=Reg03 + i*Img03;  
gR01Om0=-(Reg01+ i*Img01); 

gA03Om0= - Reg03 + i*Img03;  
gA01Om0= -(Reg01- i*Img01); 



gR03Om5=Reg03Om5 + i*Img03Om5;  
gR01Om5=-(Reg01Om5+ i*Img01Om5); 

gA03Om5= - Reg03Om5 + i*Img03Om5;  
gA01Om5= -(Reg01Om5- i*Img01Om5); 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EE=E(1);

E5= EE + OmM ;
 E0= EE;
 
 E5R= E5 +j*G;
 E0R= E0 +j*G;
 E5A= E5 -j*G;
 E0A= E0 -j*G;
 
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
n0= tanh(E0/(2*Temp));
n5= tanh(E5/(2*Temp)) ;
%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%


K1R = ( gR01Om0  )./( gR03Om0  ) ; 
K1A = ( gA01Om0  )./( gA03Om0  ) ; 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    for ind=2:length(x)
     
      %    DN=0.05+(indDiff-1)*0.1;
          
          DN=0.05;
    Diff(ind)=(1-DN)*( 1 - tanh((x(ind)- Rsuper)/0.025))/2 + DN ;
    
    if (indF==16)
    Diff(ind)=1;
    end
    
Grad2A(ind)= 0;
Grad2R(ind)= 0;

  Grad1R(ind)= Diff(ind);    
  Grad1A(ind)= Diff(ind);
    
    end   
      Diff(1)=Diff(2);
      Grad1R(1)=Grad1R(2);
      Grad1A(1)=Grad1A(2);
      
      Grad2R(1)=Grad2R(2);
      Grad2A(1)=Grad2A(2);
      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5

% DT1 = ( 1- imag(gR01).^2 + imag(gR03).^2 - real(gR01).^2 + real(gR03).^2 ) ;
 ST1= (real(gR03Om0).^2-imag(gR03Om0).^2);
 
 E0R= EE +j*G;
 E0A= EE -j*G;
 
 E5R= EE +j*G + OmM;
 E5A= EE -j*G + OmM;
 
  X1R= 2*( -i*E0R.*gR03Om0 + Op'.*gR01Om0 + timpSO'/2 );
 X1A=  2*( -i*E0A.*gA03Om0 + Op'.*gA01Om0 + timpSO'/2 );

%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%
       
H1=-  ( timp*ST1 + real(gR03Om0)*(i*OmM + 2*G));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       

%dnE=1;
SourceR= 0*2*i*gR01Om0 ;
SourceR(length(x))=2*i*gR01Om0(length(x));

%SourceR= 2*i*( gR01Om0 );

SourceA=0*2*i*gA01Om0 ;
SourceA(length(x))=2*i*gA01Om0(length(x));

%SourceA= 2*i*( gA01Om0 );
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%StepX=x(2)-x(1);

AR=zeros(length(x),length(x));
AA=zeros(length(x),length(x));



indY=1;
AR(1,1) = (- Grad1R(1)/StepX^2)*grd + X1R(indY) ;
AR(1,2) =  ( Grad1R(2)/StepX^2 )*grd  ;

AA(1,1) = (- Grad1A(1)/StepX^2 )*grd + X1A(indY) ;
AA(1,2) =  ( Grad1A(2)/StepX^2)*grd  ;

indY=length(x);
AR(indY,indY) = ( Grad2R(indY)/StepX - Grad1R(indY-1)/StepX^2 )*grd + X1R(indY) ;
AR(indY,indY-1) = ( - Grad2R(indY-1)/StepX^2 + Grad1R(indY-1)/StepX^2 )*grd ;

AA(indY,indY) =  ( Grad2A(indY)/StepX - Grad1A(indY-1)/StepX^2 )*grd + X1A(indY) ;
AA(indY,indY-1) =  ( - Grad2A(indY-1)/StepX^2 + Grad1A(indY-1)/StepX^2)*grd  ;

for indY=2:(length(x)-1)
   % B(indY,indY)= H2(indY);

for indX=1:(length(x))
    
if (indX==indY)
    
        
%A(indY,indX) = - 8*Diff(indX)/(4*StepX^2) ;
AR(indY,indX) = ( (  Grad2R(indY)/StepX - ( Grad1R(indY-1) + Grad1R(indY))/StepX^2))*grd + X1R(indY) ;
AA(indY,indX) = ( (  Grad2A(indY)/StepX - ( Grad1A(indY-1) + Grad1A(indY))/StepX^2) )*grd + X1A(indY) ;

end

if (indX==(indY-1)) 
AR(indY,indX) = (  Grad1R(indX)/StepX^2 - Grad2R(indX)/StepX^2)*grd ;
AA(indY,indX) = (  Grad1R(indX)/StepX^2 - Grad2R(indX)/StepX^2)*grd ;

end

if (indX==(indY+1))
AR(indY,indX) = (Grad1R(indY)/StepX^2 )*grd;

AA(indY,indX) = (Grad1A(indY)/StepX^2 )*grd;

end

end

end

ySolR= AR\conj(SourceR');
ySolA= AA\conj(SourceA');

  dg3R= - gR03Om0.*K1R.*conj(ySolR');
  dg3A= - gA03Om0.*K1A.*conj(ySolA');
  
 %  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


muS=i*( n5.*dg3R - n0.*dg3A)/OmM;

muSTot= muSTot+muS*StepE;

EEE=[EEE EE];

DDDiss=[DDDiss (muS(length(muS))) ];
%DDD=[DDD DT1(1)];
%SSS=[SSS ST1(1)];
Diss= Diss- (muS(length(muS)))*StepE;
    end
    
   % figure
   % plot(EEE,imag(DDDiss))
    
   DDiss=[DDiss Diss];
      
   %save (fileSavemuS,'x', 'muSTot');
         
    end

 figure
 plot(TT,imag(DDiss))
 save (fileSave,'TT', 'DDiss');

end
end
